[workspace]

members = [
    "replicator_bin",
    "replicator_lib",
]

[workspace.dependencies]
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
russh = "0.44"
russh-keys = "0.44"
async-trait = "0.1.52"
log = "0.4"
env_logger = "0.9"
russh-sftp = "2.0.0-beta.2"

